### ISSUE TITLE
Dependency on VSEssentials.dll breaks when using --addModPath

### ISSUE THREAD

**Issue by JyeGuru** [egocarib/Vintage-Story-Mods#1]
When launching a server using `--addModPath` to store mods somewhere other than the server's actual mod folder, this mod fails to load:

```
6.7.2021 00:44:48 [Error] [egocaribautomapmarkers] An exception was thrown when trying to start the mod:
System.IO.FileNotFoundException: Could not load file or assembly 'VSEssentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'VSEssentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at egocarib_AutoMapMarkers.MapMarkerMod.Start(ICoreAPI api)
   at Vintagestory.Common.ModLoader.TryStartSystem(Mod mod, ModSystem system, ICoreAPI api, ModEventPhase phase)
```

Workaround is to copy VSEssentials.dll into the same additional mod path folder alongside the mod zip, however this also generates a warning because the game attempts to load Essentials twice.

Reproduction steps:
- Create a folder somewhere with this mod zip in it
- Run the server using `VintagestoryServer.exe --addModPath "folder\with\mod.zip"`
- Observe this error in the log

Why/Use Case:
I host multiple instances of VS on the server I run for friends with different sets of mods. Using `--addModPath` along with `--dataPath` I can use the single install of the game to do this and store separate configs.

**Comment by egocarib** [comment]
@JyeGuru Thanks for the notes!

This should hopefully be fixed in the next version that I'm working on - the mod is now compiled into a .dll with assets, so I believe that should fix the reference error. In general I've made a number of other improvements to ensure the mod can work better on a multiplayer server (and I've been testing it out myself with a local server). I'll try this scenario out too before I release the next version.

**Comment by egocarib** [comment]
Should be fixed now in the latest version - I tested it on my local server without issues.
